### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by ptrsp** [andredxc/ICNInstallation#1]
hello sir, may i know your email? I'm currently working on icn sdn on my thesis. I've followed the step-by-step environment installation on github, but I'm still confused about the simulation steps that need to be run. Therefore, would you please provide your email to make it easier for me to consult.

**Comment by andredxc** [comment]
Hi, this repository contains the code from https://github.com/gabrielmleal/icnsdnnetwork with a few changes possibly. Unfortunately, I was also unable to install it and make it work. I ended up remaking this with a different approach in the repository https://github.com/andredxc/icnsimulations

**Comment by andredxc** [comment]
Feel free to send me an email at andredxc@gmail.com
